apiVersion: v2
name: openshift-logging-deployment
description: Installs and configures OpenShift Logging by calling the Chart openshift-logging
version: 1.0.0
dependencies:
  - name: openshift-logging
    version: ~1.0.23
    repository: https://charts.stderr.at/
  - name: helper-loki-bucket-secret
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-loki-bucket-secret.enabled
maintainers:
  - name: tjungbauer
