apiVersion: v2
name: clusterconfig
description: Installs cluster configuration which is usually valid for ALL clusters
version: 1.0.0
dependencies:
  - name: generic-cluster-config
    version: "1.0.2"
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbau
