apiVersion: v2
name: network-observer
description: Install the Network Observer Operator along side with Loki
version: 1.0.3
dependencies:
  - name: helper-operator
    version: ~1.0.18
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~3.0.6
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: helper-loki-bucket-secret
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-loki-bucket-secret.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
